name: CI Tests

on:
  push:
    branches:
      - '**'

jobs:

  test-api:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      env:
        TEST_CONTAINER_IMG: api_tester
      run: |
        docker compose build api
        docker build -t ${TEST_CONTAINER_IMG} -f api/app/tests/Dockerfile .
        docker run --rm -v ${PWD}/api/app/tests:/app/tests ${TEST_CONTAINER_IMG}
